import { WeddingConfig } from "@/types";

export const WEDDING_CONFIG: WeddingConfig = {
  groom: {
    nameEn: "MOHAMED",
    nameAr: "محمد",
    titleEn: "Groom",
    titleAr: "العريس",
  },
  bride: {
    nameEn: "MENNA",
    nameAr: "منة",
    titleEn: "Bride",
    titleAr: "العروس",
  },
  monogram: "M × M",
  date: {
    iso: "2026-09-10T19:00:00+02:00",
    displayEn: "10 · 09 · 2026",
    displayAr: "١٠ · ٠٩ · ٢٠٢٦",
    day: "10",
    monthEn: "SEPTEMBER",
    monthAr: "سبتمبر",
    year: "2026",
  },
  city: {
    en: "CAIRO",
    ar: "القاهرة",
  },
  country: {
    en: "EGYPT",
    ar: "مصر",
  },
  venue: {
    nameEn: "Grand Ballroom & Gardens",
    nameAr: "القاعة الكبرى والحدائق",
    addressEn: "Cairo, Egypt",
    addressAr: "القاهرة، مصر",
    mapsUrl: "https://maps.google.com/?q=Cairo,Egypt",
    isConfirmed: false, // Set true once the official venue is finalized
  },
  eventTime: {
    displayEn: "Coming Soon",
    displayAr: "قريباً",
    isConfirmed: false,
  },
  timeline: [
    {
      time: "07:00 PM",
      timeAr: "٠٧:٠٠ م",
      titleEn: "Guest Arrival & Welcome Drinks",
      titleAr: "استقبال الضيوف والمشروبات الترحيبية",
      descriptionEn: "Soft live classical strings & champagne reception",
      descriptionAr: "موسيقى وترية حية واستقبال مميز",
    },
    {
      time: "08:00 PM",
      timeAr: "٠٨:٠٠ م",
      titleEn: "The Wedding Celebration Entry",
      titleAr: "مراسم الدخول والاحتفال",
      descriptionEn: "Welcoming Mohamed & Menna into a lifetime together",
      descriptionAr: "الترحيب بمحمد ومنة وبداية رحلة العمر",
    },
    {
      time: "09:30 PM",
      timeAr: "٠٩:٣٠ م",
      titleEn: "Royal Banquet Dinner",
      titleAr: "مأدبة العشاء الفاخرة",
      descriptionEn: "Curated fine dining & toast",
      descriptionAr: "قائمة عشاء راقية ونخب المحبة",
    },
    {
      time: "10:30 PM",
      timeAr: "١٠:٣٠ م",
      titleEn: "Cake Cutting & Midnight Celebration",
      titleAr: "تقطيع الكعكة والاحتفال الليلي",
      descriptionEn: "Music, dancing & cherished moments",
      descriptionAr: "موسيقى، رقص ولحظات لا تُنسى",
    },
  ],
  music: {
    enabled: true,
    defaultVolume: 0.35,
    titleEn: "Mohamed & Menna — Wedding Theme",
    titleAr: "لحن زفاف محمد ومنة",
    artist: "Romantic Orchestra",
    customAudioUrl: "/audio/wedding-music.mp3",
  },
  heroImage: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=2000&q=85",
  venueImage: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1600&q=85",
  closingImage: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=2000&q=85",
  galleryImages: [
    {
      src: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=85",
      alt: "Editorial couple silhouette under warm cinematic lighting",
      captionEn: "Two souls, one timeless journey",
      captionAr: "روحان، ورحلة خلود",
      aspectRatio: "portrait",
    },
    {
      src: "https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=1200&q=85",
      alt: "Close up of gold wedding rings with soft candle highlights",
      captionEn: "The sacred vows in gold",
      captionAr: "عهد المحبة المخلد بالذهب",
      aspectRatio: "square",
    },
    {
      src: "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?auto=format&fit=crop&w=1200&q=85",
      alt: "Champagne flute toast and golden bokeh reflections",
      captionEn: "To love, laughter & forever",
      captionAr: "لنخب الحب والضحكات والأبدية",
      aspectRatio: "landscape",
    },
    {
      src: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1200&q=85",
      alt: "Delicate couture bridal lace & floral details",
      captionEn: "Elegance woven into every thread",
      captionAr: "أناقة نُسجت في كل تفصيل",
      aspectRatio: "tall",
    },
    {
      src: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=85",
      alt: "Candlelit luxury dining table under the night sky",
      captionEn: "An evening of unforgettable memories",
      captionAr: "أمسية من الذكريات الخالدة",
      aspectRatio: "landscape",
    },
    {
      src: "https://images.unsplash.com/photo-1544078751-58fee2d8a03b?auto=format&fit=crop&w=1200&q=85",
      alt: "Romantic evening ambiance at luxury grand venue",
      captionEn: "Under the Cairo midnight stars",
      captionAr: "تحت نجوم سماء القاهرة",
      aspectRatio: "portrait",
    },
  ],
  social: {
    ogTitle: "Mohamed & Menna — The Wedding Invitation",
    ogDescription: "Join Mohamed & Menna as they celebrate their love on 10 September 2026 in Cairo.",
    ogImage: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&h=630&q=85",
  },
};
